Algoritmo "01_contagem"
// 
//  
// Autor(a)    : MARIA EDUARDA ORSI


Var
// Seção de Declarações das variáveis
 
   cont,comeco,fim:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval("Digite o valor inicial: ")
      leia(comeco)
      escreval("Digite o valor final: ")
      leia(fim)

      para cont de comeco ate fim faca
         escreval("cont => ", cont)
fimpara


Fimalgoritmo