Algoritmo "06_CONTADOR"
// 
//  
// Autor(a)    : MARIA EDUARDA ORSI

Var
// Seção de Declarações das variáveis 
    cont, acumulador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

         para cont de 1 ate 10 faca
           escreval("Valor do contador ->",cont)
           acumulador<-acumulador+cont
   fimpara

          escreval ("O valor acumulado é: ",acumulador)

Fimalgoritmo