Algoritmo "02_TABUADA"
// 
//  
// Autor(a)    : MARIA EDUARDA ORSI

Var
// Seção de Declarações das variáveis 
    cont,numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Digite um numero: ")
         leia(numero)


         para cont de 1 ate 10 faca
              escreval(cont," x ",numero," = ",cont*numero)
fimpara


Fimalgoritmo