Algoritmo "15_REPITA.ATE"
// 
//  
// Autor(a)    : MARIA EDUARDA O
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
      esc: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   repita
      escreval("Qual é a melhor escola de RP?")
      leia(esc)
   ate (esc = "ETEC MCM")

   escreval ("Muito bem, resposta correta!!!")


Fimalgoritmo